### ISSUE TITLE
Сделать приятное отображение для отдельного продукта

### ISSUE THREAD

**Issue by MikeKondr99** [MikeKondr99/PizzaStoreSln#4]

**Comment by Bread92** [comment]
![image](https://user-images.githubusercontent.com/48021337/178442592-eade05b3-1abf-4c87-a9a2-4ad8c08cafb7.png)

**Comment by Bread92** [comment]
![image](https://user-images.githubusercontent.com/48021337/179265373-e150a974-44e3-4d5d-880e-9d8f0b6a41de.png)
